### ISSUE TITLE
Compatibility with @discordjs/opus v0.9.0

### ISSUE THREAD

**Issue by mtripg6666tdr** [amishshah/prism-media#109]
#### Issue:

It seems that prism-media has no compatibility with @discordjs/opus v0.9.0
Is it going to support the latest @discordjs/opus?

#### Steps to reproduce:

1. create new npm project
2. install latest prism-media
3. install latest @discordjs/opus

#### Further details:
- Operating System: not applicable
- Node.js version: not applicable
- Commit I'm using: v1.3.4

**Comment by elliotsayes** [comment]
What is the last compatible version of @discordjs/opus ?

**Comment by mtripg6666tdr** [comment]
> What is the last compatible version of @discordjs/opus ?

v0.8.0

**Comment by xSkeletor** [comment]
Any ETA on this, @amishshah? It's been a little over 3 months since @discordjs/opus 0.9.0 was released, and the version difference between the packages has meant that my project has been unable to work for a while.

**Comment by Starkrights** [comment]
@xSkeletor Is your issue something screaming about conflicting peer dependencies between prism-media & @djs/opus?

If so, try running `npm install --legacy-peer-deps`. That seemed to have cleared everything up for me.

Source: Recommended from the npm error on install, and from [this](https://stackoverflow.com/questions/71517176/npm-install-fails-with-conflicting-peer-dependency-react16-14-0) SO post on a similar issue.

**Comment by mtripg6666tdr** [comment]
Currently we have no choice but forking this or running `npm i` with `--legacy-peer-deps`, however the `legacy-peer-deps` option simply skips the checks of peer deps so we may be led to overlook of any other peer dependency conflicts. So it shouldn't be the recommended option.
