### ISSUE TITLE
"Latest" published version is 0.0.4 instead of 1.2.0

### ISSUE THREAD

**Issue by Favna** [amishshah/prism-media#38]
#### Issue:

When installing the "latest" tag from NPM it will install v0.0.4 instead of v1.2.0. 

![image](https://user-images.githubusercontent.com/4019718/72929727-aef71200-3d5a-11ea-9e81-f87fd72cfe3f.png)

#### Steps to reproduce:

1. Go to https://www.npmjs.com/package/prism-media
2. Go to versions tab
3. Observe entries

---

1. Run `npm install prism-media@latest`
2. Check `pacakge.json` in `node_modules/prism-media`
3. Observe version

![image](https://user-images.githubusercontent.com/4019718/72930903-380f4880-3d5d-11ea-8bff-608a71424803.png)

#### Further details:
- Operating System: N.A.
- Node.js version: N.A.
- Commit I'm using: N.A.

**Comment by amishshah** [comment]
This is not something I can fix as 0.0.4 was simply released after 1.2.0. As a side note, you should really be specifying versions rather than `latest` when installing.

**Comment by Favna** [comment]
Ao informed me on the Dirigeants Discord as well. To be honest I do specify version but I just noticed when browsing to the package on yarnpkg site.
