### ISSUE TITLE
throw Error(`capture_pattern is not ${OGGS_HEADER}`)

### ISSUE THREAD

**Issue by KM0KA** [amishshah/prism-media#42]
#### Issue:

Aloha All!

I migrated over to V12 with the hope that all issues with Opus playback would go away. Running into the same issues.

I pull in an MP3 file from cloudFront. I then save this file locally to convert it to opus. 

I run the routines as shown into the "mp3 to opus" example. I label the suffix ".ogg" and everything seems to work as planned. I can play the MP3 file without any issues. It is my understanding that Prism uses FFmpeg to convert an MP3 file to opus on the fly. Since any MP3 submitted for playback works flawlessly, I am assuming that the behind the scene conversion does work. I am attempting to convert the files to save on response time to the users. The MP3 files can become quite large. I am currently testing with a 14 second MP3.

I run into a wall anytime I am trying to convert, store, then retrieve the "opus/ogg" file for playback.

When I go to actually play the Opus Ogg file, it blows up with this error:

throw Error(`capture_pattern is not ${OGGS_HEADER}`)

Here is the full trace:

Error: capture_pattern is not OggS
    at OggDemuxer._readPage (/home/centos/discord/v12/node_modules/prism-media/src/opus/OggDemuxer.js:56:13)
    at OggDemuxer._transform (/home/centos/discord/v12/node_modules/prism-media/src/opus/OggDemuxer.js:36:27)
    at OggDemuxer.Transform._read (_stream_transform.js:191:10)
    at OggDemuxer.Transform._write (_stream_transform.js:179:12)
    at doWrite (_stream_writable.js:454:12)
    at writeOrBuffer (_stream_writable.js:436:5)
    at OggDemuxer.Writable.write (_stream_writable.js:327:11)
    at ReadStream.ondata (_stream_readable.js:708:22)
    at ReadStream.emit (events.js:321:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at ReadStream.Readable.push (_stream_readable.js:214:10)
    at internal/fs/streams.js:242:14
    at FSReqCallback.wrapper [as oncomplete] (fs.js:496:5)

#### Steps to reproduce:

Here is the convert code following the "mp3 to opus" example:

const convert   = fs.createReadStream(mp3File);
const opus       = new prism.opus.Encoder({ rate: 48000, channels: 2, frameSize: 960 });

const transcoder = new prism.FFmpeg({
            args: [
                '-analyzeduration', '0',
                '-loglevel', '0',
                '-f', 's16le',
                '-ar', '48000',
                '-ac', '2',
            ],
            });
            
let test =  __dirname + '/podcasts/' + identifier + '.ogg';

convert.pipe(transcoder).pipe(opus).pipe(fs.createWriteStream(test));

The above code successfully writes out the conversion, even though the format appears to be incorrect.

I have tried:

convert.pipe(transcoder).pipe(fs.createWriteStream(test));

convert.pipe(opus).pipe(fs.createWriteStream(test));

with the same results.

Here is the code for the playback following new V12 conventions:

const dispatcher = connection.play(fs.createReadStream(audioFile), { type: 'ogg/opus' });

Help! 

Thanks in advance!

#### Further details:
- Operating System: CENTOS 7
- Node.js version: 13.9
- Commit I'm using:

**Comment by amishshah** [comment]
The issue here is that the `OpusEncoder` provides a stream of Opus packets -- these cannot simply be written to a file as they aren't in a container. To get around this, you can consider using a package such as [`node-ogg`](https://www.npmjs.com/package/ogg) to put the Opus packets into an Ogg container.

I'm planning to add a basic encoder in the future for this specific reason! :)
