### ISSUE TITLE
Crashing with opusscript

### ISSUE THREAD

**Issue by isolin** [amishshah/prism-media#45]
Following a simple tutorial like [this](https://gabrieltanner.org/blog/dicord-music-bot) causes a `null` exception that crashes the whole streaming.

Reproduce:
1. Install **opusscript**
2. Call `conn.play(what_ever_source)`
3. You get 
```
TypeError: Cannot convert "null" to int
TypeError: Cannot convert "null" to int
at (anonymous) (file:///c:/Users/pc/Documents/Discord%20Bot/node_modules/opusscript/build/opusscript_native_wasm.js:8:1741)
```

This is caused by `Opus.js:55` passing a `null` as ` framesize which later crashes `opusscript`. In my case, `this._options.frameSize === 960` so it's correctly filled.

```js
  _encode(buffer) {
    return this.encoder.encode(buffer, Opus.name === 'opusscript' ? null : this._options.frameSize);
  }
```

I have no deeper insight why there is this name check, but after I deleted it, it worked like a charm. Could you please fix that? This works fine

```js
  _encode(buffer) {
    return this.encoder.encode(buffer, tthis._options.frameSize);
  }
```

**Comment by amishshah** [comment]
Thanks for raising this issue!

I can't remember why I added this check for `opusscript` in the encode function, I see no reason for it to be there now. I've gone ahead and removed it, should work now!

The fix has now been released in [v1.2.2](https://github.com/amishshah/prism-media/releases/tag/v1.2.2).

Thanks again for going to the effort to look into this issue :)
