### ISSUE TITLE
Update peer dependency for @discordjs/opus

### ISSUE THREAD

**Issue by sasjafor** [amishshah/prism-media#52]
#### Issue:
When writing a discord bot using discord.js and @discordjs/opus, the npm install command fails since it can't satisfy the prism-media peer dependency for @discordjs/opus when using "@discordjs/opus": "0.3.3" in package.json

#### Steps to reproduce:
Add "discord.js": "^12.4.1" and "@discordjs/opus": "0.3.3" to package.json and run npm i.

#### Further details:
- Operating System: Ubuntu
- Node.js version: 15.2.1
- prism-media requirement: ^1.2.2 from discord.js version ^12.4.1

**Comment by amishshah** [comment]
Done, released in `prism-media@v1.2.3`
