### ISSUE TITLE
Feature request: Enable volume fading functionality in VolumeTransformer

### ISSUE THREAD

**Issue by MHebes** [amishshah/prism-media#54]
#### Problem

It is currently impossible, using VolumeTransformer, to make a smooth transition between volumes.

#### Ideal solution

- Add `fadeTime` or `fadeSpeed` to options, change `this.volume` to semantically mean "target volume", and add logic for smoothly transitioning between target volumes in the `_transform` method.
- Make `setVolume` `async`, to be resolved or rejected when the transition is complete.
- Add `setFadeTime`, etc. methods.

#### Other alternatives

Make a new VolumeTransformer variant, SmoothVolumeTransformer, which implements the above functionality.

**Comment by MHebes** [comment]
For anyone who finds this, I made a version that works OK [here](https://gitlab.com/-/snippets/2049055). It's not perfect but it works well for me as a simple drop-in replacement for `VolumeTransformer`.

**Comment by amishshah** [comment]
I believe this is outside the scope of this library - it seems a bit opinionated to include.
