### ISSUE TITLE
Error: spawn ENOMEM

### ISSUE THREAD

**Issue by BR88C** [amishshah/prism-media#55]
#### Issue:
I am getting this error, seemingly at random, after trying to start a stream:
```
(node:14009) UnhandledPromiseRejectionWarning: Error: spawn ENOMEM
    at ChildProcess.spawn (internal/child_process.js:408:11)
    at Object.spawn (child_process.js:553:9)
    at Function.create (/home/br88c/github/peter/node_modules/prism-media/src/core/FFmpeg.js:155:25)
    at new FFmpeg (/home/br88c/github/peter/node_modules/prism-media/src/core/FFmpeg.js:44:27)
    at StreamDownloader (/home/br88c/github/peter/node_modules/discord-ytdl-core/index.js:45:24)
    at Object.play (/home/br88c/github/peter/src/modules/streamhandler.js:57:22)
    at Object.execute (/home/br88c/github/peter/src/commands/play.js:135:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
It appears it's having trouble with starting FFMPEG, but I am unsure of the cause. Normally it works completely fine, then it'll start throwing this error and will continue to throw this error until I restart my code. Help is greatly appreciated!

#### Further details:
- Operating System: Debian 10
- Node.js version: 12.20.0
- Commit I'm using: 1.2.3

**Comment by kyranet** [comment]
`ENOMEM` is the [error code](https://www-numi.fnal.gov/offline_software/srt_public_context/WebDocs/Errors/unix_system_errors.html) for "Out of memory", this might indicate that your project does not have enough RAM to function.

**Comment by BR88C** [comment]
Ah ok, I see the issue I'm having now.
Every time I start a stream, I spawn a new FFMPEG process. However, even when the stream ends whatever data that was buffered stays buffered. Is there any way to resolve this?

**Comment by BR88C** [comment]
Closing as I found a solution (I made sure the `close` event was being emitted)

**Comment by Lioness100** [comment]
I'm getting the same issue; could you please elaborate on your solution? Do you mean you manually emitted the `close` event?

**Comment by BR88C** [comment]
I worded this incorrectly: I'm emitting a close event on the read steam I'm creating. That then runs this code block:
```
outputStream.on("close", () => {
    transcoder.destroy();
    opus.destroy();
});
```

**Comment by Lioness100** [comment]
Would it help to call `outupStream.destroy()` as well?

**Comment by BR88C** [comment]
I don't believe `outputStream` has a `destroy` method, as it's just and `inputStream` being piped through `opus`. I'm just calling `destroy` on `opus` and `transcoder`.

**Comment by Lioness100** [comment]
I'm just going off of typescript intellisense (using `discord-ytdl-core`)

![image](https://user-images.githubusercontent.com/65814829/110245836-e743ba80-7f32-11eb-8ad1-a5bd28a318e5.png)
![image](https://user-images.githubusercontent.com/65814829/110245839-ea3eab00-7f32-11eb-9d46-1b60688747cb.png)
![image](https://user-images.githubusercontent.com/65814829/110245841-eca10500-7f32-11eb-90a5-2d2f9219efd5.png)
![image](https://user-images.githubusercontent.com/65814829/110245843-ef035f00-7f32-11eb-8d36-9565b403b9ab.png)

**Comment by Lioness100** [comment]
Hey, just checking in again to see if you can answer my last question.

**Comment by BR88C** [comment]
Sorry I haven't responded, in the terms of `discord-ytdl-core`, you just need to emit a `close` event on the stream you are creating. Say you have this code block to create your stream:
```js
const stream = ytdl(song.url, {
    opusEncoded: true,
    highWaterMark: 1 << 20,
    quality: song.format,
});
```
All I'm doing is whenever there is an unexpected close, which in the case of a Discord bot can be caused by it leaving or being disconnected from a VC, a stop command being ran, etc (Any time the stream stops before the audio is over), I emit the close event on the stream as follows:
```js
stream.emit(`close`);
```
That then fires this code internally within `discord-ytdl`core`:
```js
outputStream.on("close", () => {
    transcoder.destroy();
    opus.destroy();
});
```

**Comment by Lioness100** [comment]
Thank you!

**Comment by Lioness100** [comment]
I don't know why I waited so long to comment on this but the issue is still occurring and it's definitely affecting the usability of my bot. Here's [my code](https://github.com/arimajs/Arima/blob/main/src/lib/structures/quiz/Game.ts#L168) if you'd like to take a look.

**Comment by Lioness100** [comment]
This is a cry for help :)

**Comment by Lioness100** [comment]
A desperate cry for help :'(

**Comment by adrifcastr** [comment]
What is Amish supposed to do? Download more RAM for you? Like please just move on.
