### ISSUE TITLE
How to calculate frameSize when encoding?

### ISSUE THREAD

**Issue by OnkelTem** [amishshah/prism-media#64]
Currently Encoder requires from us to provide the proper `frameSize` parameter: 
```js
  const opus = new prism.opus.Encoder({ rate: 48000, channels: 1, frameSize: 960 });
```

I assume 'requires' in the TypeScript meaning, as there's no way to omit it.

There are few concerns.

1) [The official Opus docs](https://www.opus-codec.org/docs/html_api/group__opusencoder.html) say:

> **frame_size** is the **duration** of the frame in samples (per channel).

while prism applies a [different meaning](https://hydrabolt.me/prism-media/?api#new-opus.Encoder) to the same thing:

> the frame size **in bytes** to use (e.g. 960 for stereo audio at 48KHz with a frame duration of 20ms)

which I believe brings some confusion. 

2) And what is more important, is that it's not clear _how to calculate it_.
Obviously, if it can be calculated automatically then it doesn't need to be **_required_**, does it?
If not - then please, explain how to calc it.

**Comment by amishshah** [comment]
I agree that the meanings are confusing. The Opus documentation actually offers yet another definition for `frame_size` ([see `opus_encode`](https://www.opus-codec.org/docs/html_api/group__opusencoder.html)):

> [in] | frame_size | int: Number of samples per frame of input signal

This is the definition used by the encoder. For example, a value of 960 for this means that for each distinct Opus packet, each audio channel of the packet is formed from 960 bytes of raw audio.

So with that in mind, it's sort of annoying, but "frame size" can either be a time duration or a size measurement in bytes.

You can swap between the two fairly easily as long as you have the original sample rate.

For example, for a sample rate of 48000Hz and a frame size of 20ms (=0.02 seconds), the frame size for **one channel** given **in bytes** is `48000 * 0.02 = 960`. Therefore, we would need 960 bytes _per channel_. For stereo audio, a single Opus packet would therefore require `960 * 2 = 1920` bytes of audio, 960 for each channel.

---

While you can derive the frame size in ms from the `TOC` byte of an Opus packet, you _can't_ derive the sample rate of the audio (as far as I'm aware). This is given by the OpusHead in the audio container. Technically, this can all be inferred by the decoder if it is given the OpusHead along with the Opus packets, however the OpusHead isn't always easily accessible to the Decoder stream. This might be something I look into for the next version of prism.

**Comment by OnkelTem** [comment]
Thank you very much for the explanation. I believe it can be added to the README almost w/o edits!

**Comment by OnkelTem** [comment]
There's one trivial question left :)

So what is rate really? A bitrate in bits per second?

**Comment by amishshah** [comment]
It's different to the bitrate (although I assume that a higher sample rate would also give a higher bitrate).

The sample rate is the number of times per second that you sample an audio stream. For example, 48000Hz means that you sample some audio source 48000 times a second. The [Wiki article](https://en.wikipedia.org/wiki/Sampling_(signal_processing)#Sampling_rate) on it probably explains it better than I can!

**Comment by OnkelTem** [comment]
Yeah, I know _that_ sampling rate. I thought that 48000 is ~48kbps.

So how to configure Encoder for different use cases: http://wiki.hydrogenaud.io/index.php?title=Opus#Indicative_bitrate_and_quality ?

**Comment by amishshah** [comment]
You can make use of the `setBitrate` method of the Opus stream ([see docs for it here](https://hydrabolt.me/prism-media/?api#opus.Encoder#setBitrate)):
```ts
opusEncoder.setBitrate(48000); // set bitrate to 48kbps
```

**Comment by OnkelTem** [comment]
Ah, good.

> the bitrate to use use, e.g. 48000

Ahh, that same confusing 48000 number, which reminds herzes, but means now bits, if I get it right.

**Comment by amishshah** [comment]
No problem :smile: Will close now that the issue is resolved.
