### ISSUE TITLE
So how to specify the only thing which matters - the bitrate?

### ISSUE THREAD

**Issue by OnkelTem** [amishshah/prism-media#65]
After playing for a while I now see that the options we pass to the encoder/decoder don't really matter.
The only thing which does matter would be the bitrate, but there is no such an option.
How is that?

Also, I checked out the underlying @deiscordjs/opus lib and well... it doesn't even have the Frame Size option, only the sampling rate (which should always be 48kHz according to the [RFC](https://tools.ietf.org/html/rfc7845.html#page-14)) and the number of channels.

So now I'm really confused with all that.
If this lib is using @deiscordjs/opus under the cover, then why requiring from us to provide the frameSize at all?

**Comment by amishshah** [comment]
To answer the frame size question, we also support [opusscript](https://www.npmjs.com/package/opusscript) which _does_ require a `frameSize` when encoding.

For setting bitrate, you should be able to via [`setBitrate`](https://hydrabolt.me/prism-media/?api#opus.Encoder#setBitrate):

```js
const encoder = new opus.Encoder(options);
encoder.setBitrate(96000);
```
