### ISSUE TITLE
Prism Documentation Not Found

### ISSUE THREAD

**Issue by FireNameFN** [amishshah/prism-media#81]
This link doesn't work: https://hydrabolt.me/prism-media/?api

![image](https://user-images.githubusercontent.com/37689533/121769974-c2459000-cb90-11eb-9f36-2995b411cf08.png)

**Comment by hieyou1** [comment]
Originally in #84, but just saw that it was a near-duplicate and thought I'd post it here.

#### Issue:
The "Documentation" link on NPM leads to a 404 error page.

The link that's currently on there is: [https://hydrabolt.me/prism-media](https://hydrabolt.me/prism-media)
It should be: [https://amishshah.github.io/prism-media/](https://amishshah.github.io/prism-media/)

Also, the link to the Prism website on your website, [https://hydrabolt.me](https://hydrabolt.me), needs to be updated.

Or make [https://hydrabolt.me/prism-media](https://hydrabolt.me/prism-media) redirect to [https://amishshah.github.io/prism-media/](https://amishshah.github.io/prism-media/) to make it a bit less confusing for new users :)

#### Steps to reproduce:
1. Click the documentation link in the README on NPM
or
1. Go to [https://hydrabolt.me](https://hydrabolt.me)

#### Further details:
- Operating System: N/A
- Node.js version: N/A
- Commit I'm using: v1.3.1 as posted on NPM

EDIT: Documentation link on README at [https://amishshah.github.io/prism-media/](https://amishshah.github.io/prism-media/) is also broken.
